# Generated by Django 4.2 on 2024-08-09 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 18, 40, 27, 267320)),
        ),
    ]
