# Generated by Django 4.2 on 2024-08-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usersignup_dummy_alter_usersignup_expired_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='expired_date',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='has_expired',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='purchase_date',
        ),
    ]
