# Generated by Django 4.2 on 2024-08-09 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_usersignup_expired_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 18, 46, 58, 99194)),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='has_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 18, 46, 58, 100193)),
        ),
    ]
