# Generated by Django 4.2 on 2024-08-09 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usersignup_expired_date_usersignup_has_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 18, 52, 51, 629259)),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 18, 52, 51, 630309)),
        ),
    ]
