# Generated by Django 5.0.7 on 2024-07-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dataset_hyperparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='s3_storage_used',
            field=models.FloatField(default=0.0),
        ),
    ]
