# Generated by Django 4.1.13 on 2024-07-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usersignup_s3_storage_used'),
    ]

    operations = [
        migrations.DeleteModel(
            name='S3StorageUsage',
        ),
    ]
